TargetTopic:                '/move_base_simple/goal'

PenaltyWeight:              100.0

CircleObs:                  [  0.0,   0.0,   4.0, 
                               1.0,   8.0,   3.0, 
                              -8.0,   1.0,   2.0,
                              -5.0,  16.0,   5.0,
                              13.0,   2.0,   6.0,
                             -15.0, -12.0,   5.0,
                             -18.0,   6.0,   8.0,
                              12.0, -15.0,   4.0,
                              20.0,  19.0,   4.5,
                              -3.0, -18.0,   6.5]

PieceLength:                0.5

RelCostTol:                 1.0e-5

PolysNum: 50
PolyPlaneNum: 50
PolyXYBound: 25
PolyUVBound: 5

v_max: 8
a_max: 15
v_start: 2
v_end: 0

sub_pieces_num: 1
